# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a49d381dc3e55ee878b101a8ff6be459323e0c97014254c695ba64406e0d9c56f49c56e3a8d9d67584f809209c58b4747a1485662c5ed5afe3a7e0941c8220d1

test:
  secret_key_base: aaa13cd1559b7bb3b48c15f40448d85b798917da559a21b99b46a156e3a4c88e9e1a12fb91b112fbd19e0789b65c4010fc4978eeb71ac6a89fc5ab598d613fe0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
